/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
/* //src/utils/supabase/info.tsx*/
export const projectId = "auyofgzzzkkbnkdjcgcj"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1eW9mZ3p6emtrYm5rZGpjZ2NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExNjExNjYsImV4cCI6MjA3NjczNzE2Nn0.YnhPKhcfXhRLDX7cMMuh4euZwPfL7J3f4Cb55iFcgM8"